// LeetCode: 1332. Remove Palindromic Subsequences
// 1332-Remove-Palindromic-Subsequences.cpp
// Created by Victor Rogulenko
// [2022-06-08 22:59]

// You are given a string s consisting only of letters 'a' and 'b'. 
// In a single step you can remove one palindromic subsequence from s.
// Return the minimum number of steps to make the given string empty.
// A string is a subsequence of a given string if it is generated by deleting 
// some characters of a given string without changing its order. Note that 
// a subsequence does not necessarily need to be contiguous.
// A string is called palindrome if is one that reads the same backward as well 
// as forward.
// 1 <= s.length <= 1000
// s[i] is either 'a' or 'b'.

// MAJOR IDEA: If s is palindrome, res = 1, else 2

#include <string>

class Solution {
public:
    int removePalindromeSub(const std::string& s) {
        return (s == std::string(s.rbegin(), s.rend()) ? 1 : 2);
    };
};

// #bugs = 0